import nltk
stopwords = nltk.corpus.stopwords.words('english')
stopwords.append('"')
stopwords.append('.')
stopwords.append(',')
stopwords.append('')
stopwords.append('(')
stopwords.append(')')
stopwords.append('+1')
stopwords.append('--')
stopwords.append('-1')
stopwords.append(':')
stopwords.append('&')
stopwords.append('!')
stopwords.append('?')
