import nltk
STOPWORDS = nltk.corpus.stopwords.words('english')
STOPWORDS.append('"')
STOPWORDS.append('.')
STOPWORDS.append(',')
STOPWORDS.append('')
STOPWORDS.append('(')
STOPWORDS.append(')')
STOPWORDS.append('+1')
STOPWORDS.append('--')
STOPWORDS.append('-1')
STOPWORDS.append(':')
STOPWORDS.append('&')
STOPWORDS.append('!')
STOPWORDS.append('?')
